#version: '3.1'

#사설망 생성 network 생성
networks:
  kosa_network:
    driver: bridge
#서비스 선언
services:
#was1 생성
  was1:
    image: wkdtmdgnsdev/hello-web:latest
    networks:
      - kosa_network
#was2 생성
  was2:
    image: wkdtmdgnsdev/hello-web:latest
    networks:
      - kosa_network
#nginx 생성
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ~/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - kosa_network
    depends_on:
        - was1
        - was2